### ISSUE TITLE
找不到BasicLibrary

### ISSUE THREAD

**Issue by aixinxino** [notinmood/JianyingDraft.PY#6]
[{
	"resource": "/C:/Users/TDOVO/Desktop/JianyingDraft.PY-main/draftContext.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports",
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "无法解析导入“BasicLibrary.projectHelper”",
	"source": "Pylance",
	"startLineNumber": 11,
	"startColumn": 6,
	"endLineNumber": 11,
	"endColumn": 32
}]

**Comment by notinmood** [comment]
下载代码后，要使用poetry进行安装依赖库：poetry add
