### ISSUE TITLE
无法使用还是我打开的方式有问题

### ISSUE THREAD

**Issue by lvxiaoc** [notinmood/JianyingDraft.PY#9]
1.main.py里面这句from BasicLibrary.projectHelper import ProjectHelper 似乎根本找不到文件啊。运行报错
2.projectHelper里面这句话"""
1、项目使用的时候，请将本文件复制到项目根目录下，由'__projectHelper.py' 改名为'_projectHelper.py'
2、本文件('__projectHelper.py'和'_projectHelper.py')不直接向外暴露。
3、相应的功能，请使用ProjectHelper.py内包装后的逻辑。
"""

也不知道什么意思。文件名字本来就没有两个下划线。“项目根目录”的含义是草稿的根目录么？作者要能把使用方法写的更清楚就好了

**Comment by notinmood** [comment]
嗯。是这样，项目使用poetry进行代码和第三方库的管理。运行前要进行依赖安装，“poetry add ”

**Comment by notinmood** [comment]
你看到的这个projectHelper.py 是从 BasicLibrary.PY库内复制过来的，已经处理过了。
